services:
  ray-external-worker:
    build: .
    hostname: ${WORKER_NAME:-ray-external-worker}
    container_name: ${WORKER_NAME:-ray-external-worker}
    networks:
      - ray-network
    environment:
      - RAY_HEAD_SERVICE_HOST=ray-head
      - NODE_ROLE=worker
      - LEADER_NODE=false
      - FAILOVER_PRIORITY=3
      - ENABLE_AUTO_FAILOVER=false
    shm_size: 2gb
    command: >
      bash -c "
      echo 'Worker externo iniciando...' &&
      echo 'Esperando al cluster principal...' &&
      sleep 30 &&
      echo 'Conectando al cluster existente...' &&
      ray start 
      --address=ray-head:6379 
      --num-cpus=2 
      --object-manager-port=8076
      --node-manager-port=8077 
      --min-worker-port=10002 
      --max-worker-port=19999 &&
      echo 'Worker externo conectado exitosamente!' &&
      tail -f /dev/null
      "
    volumes:
      - .:/app
    restart: unless-stopped

networks:
  ray-network:
    external: true
    name: scr_pasd_2025_ray-network
